artifact_uri: /Users/japneetkaurchawla/Downloads/YouTube Comment Analysis/dagshub/917732618626622397/39a11e108cc149e3be2cd79f48a9dc02/artifacts
end_time: 1779391124907
entry_point_name: ''
experiment_id: '917732618626622397'
lifecycle_stage: active
run_id: 39a11e108cc149e3be2cd79f48a9dc02
run_name: sophisticated-dog-56
source_name: ''
source_type: 4
source_version: ''
start_time: 1779391121715
status: 3
tags: []
user_id: Japneet-Kaur-Chawla
