artifact_uri: /Users/japneetkaurchawla/Downloads/YouTube Comment Analysis/dagshub/917732618626622397/1622a14fd39c4f46a66d974c6add6507/artifacts
end_time: 1779388014132
entry_point_name: ''
experiment_id: '917732618626622397'
lifecycle_stage: active
run_id: 1622a14fd39c4f46a66d974c6add6507
run_name: stylish-kite-696
source_name: ''
source_type: 4
source_version: ''
start_time: 1779388010896
status: 3
tags: []
user_id: Japneet-Kaur-Chawla
